#!/bin/sh

PCH_FILE="<SOME FILE THAT CONTAINS MY TEMP TODO CODE>"
PLACEHOLDER_TEXT="(alias) TEMP"


function cecho(){
    RED="\033[0;31m"
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    NC='\033[0m' # No Color
    printf "${!1}${2} ${NC}\n"
}

if grep -q "$PLACEHOLDER_TEXT" $PCH_FILE;
    then
        cecho "RED" "

        WHAT: This commit is rejected as there are some local patches applied.
        NEXT: Please remove the patch and try again."
        
        cecho "YELLOW" "
        --
        >> git apply -R ../gk-local.patch
        --
        "
        exit 1
    else
        exit 0
fi

exit 1
